FROM resin/armhf-alpine:3.4

RUN apk update && apk add \
    bash \
    git && \
    git clone https://github.com/pjb304/ic880a-gateway.git && \
    cd ic880a-gateway && \
    git checkout resin \
    ./install.sh remote

WORKDIR /opt/ttn-gateway/bin

CMD ./start.sh
